alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: discord-webhook
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h

    receivers:
      - name: discord-webhook
        webhook_configs:
          - url: "https://discord.com/api/webhooks/1442932363058483260/mL2YkWNwyQNiBxGfqbmAIwGQSdaK1mSFOGEPM2WykR0IphtjNK2JwG2PUYl-k5KqxjJb"
            send_resolved: true
