apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm-exporter
  template:
    metadata:
      labels:
        app: php-fpm-exporter
    spec:
      containers:
        - name: exporter
          image: hipages/php-fpm_exporter:latest
          args:
            - "--phpfpm.scrape-uri=tcp://backend.reservation-app.svc.cluster.local:9000/status"
          ports:
            - containerPort: 9253
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm-exporter
  namespace: monitoring
spec:
  selector:
    app: php-fpm-exporter
  ports:
    - port: 9253
      targetPort: 9253
