# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-nginx
#   namespace: reservation-app
#   labels:
#     app: backend-nginx
#     app.kubernetes.io/name: reservation-app
#     managed-by: argocd
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend-nginx
#       app.kubernetes.io/name: reservation-app
#       managed-by: argocd
#   template:
#     metadata:
#       labels:
#         app: backend-nginx
#         app.kubernetes.io/name: reservation-app
#         managed-by: argocd
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:alpine
#           ports:
#             - containerPort: 80
#           volumeMounts:
#             - name: nginx-config
#               mountPath: /etc/nginx/conf.d/default.conf
#               subPath: default.conf
#       volumes:
#         - name: nginx-config
#           configMap:
#             name: backend-nginx-config


apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nginx
  namespace: reservation-app
  labels:
    app: backend-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-nginx
  template:
    metadata:
      labels:
        app: backend-nginx
    spec:
      volumes:
        - name: shared-code
          emptyDir: {}

        - name: nginx-config
          configMap:
            name: backend-nginx-config

      initContainers:
        - name: copy-code
          image: faroukelrey19008/reservation-backend:96
          command: ["/bin/sh", "-c", "cp -R /var/www/html/* /code"]
          volumeMounts:
            - name: shared-code
              mountPath: /code

      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
