apiVersion: v1
kind: Service
metadata:
  name: backend-nginx
  namespace: reservation-app
spec:
  selector:
    app: backend-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP