apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-metrics-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-nginx     # must match service label
  namespaceSelector:
    matchNames:
      - reservation-app
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
