apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-nginx-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-nginx
  namespaceSelector:
    matchNames:
      - reservation-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
