apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: reservation-app
data:
  # Laravel App
  APP_NAME: "Reservation App"
  APP_ENV: "production"
  APP_KEY: "base64:GENERATE_THIS_WITH_php_artisan_key:generate"
  APP_DEBUG: "false"
  APP_URL: "http://reservation.local"
  
  # Database (will be overridden by mysql-config)
  DB_CONNECTION: "mysql"
  
  # Session & Cache
  SESSION_DRIVER: "file"
  CACHE_DRIVER: "file"
  DB_HOST        : "mysql"
  DB_PORT        : "3306"
  DB_DATABASE    : "reservation_db"
  DB_USERNAME    : "root"

