apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: reservation-app
type: Opaque
stringData:
  .env: |
    APP_NAME=ReservationApp
    APP_ENV=production
    APP_KEY=base64:KI/joInBC64VBcEJc/+1/HZA7fgsn5Hk0FE40iVZ5Cc=
    APP_DEBUG=false
    APP_URL=http://reservation.local

    SESSION_DOMAIN=reservation.local
    SANCTUM_STATEFUL_DOMAINS=reservation.local
    SESSION_SECURE_COOKIE=false

    DB_CONNECTION=mysql
    DB_HOST=mysql
    DB_PORT=3306
    DB_DATABASE=reservation_db
    DB_USERNAME=root
    DB_PASSWORD=1010

    CACHE_DRIVER=file
    SESSION_DRIVER=database
    QUEUE_CONNECTION=sync
    SANCTUM_EXPIRATION=1440
