apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: reservation-app
data:
  APP_NAME: "Reservation App"
  APP_ENV: "production"
  APP_KEY: "base64:v+sCJQcJqOx00RKUZjFU95UF4/z/Y5kt4zHt9i6zMv0="
  APP_DEBUG: "false"
  APP_URL: "http://reservation.local"
  APP_TIMEZONE: "UTC"
  
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_CONNECTION: "sync"