apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: reservation-app
  labels:
    app: frontend
    app.kubernetes.io/name: reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/name: reservation-app
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: reservation-app
    spec:
      # imagePullSecrets:
      #   - name: regcred
      containers:
        - name: frontend
          image: faroukelrey19008/reservation-frontend:102
          imagePullPolicy: Always
          env:
            - name: VITE_API_URL
              value: "http://reservation.local/api"
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80

          livenessProbe:
            httpGet:
              path: /
              port: 80


