# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
#   namespace: reservation-app
#   labels:
#     app: frontend
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#     argocd-image-updater.argoproj.io/image-list: frontend=faroukelrey19008/reservation-frontend
#     argocd-image-updater.argoproj.io/frontend.update-strategy: latest
#     argocd-image-updater.argoproj.io/frontend.pull-secret: regcred
#     argocd.argoproj.io/sync-options: Replace=true
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#       annotations:
#         image-version: "60"
#     spec:
#       imagePullSecrets:
#         - name: regcred
#       containers:
#         - name: frontend
#           image: faroukelrey19008/reservation-frontend:60
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 3000
#               name: http
#           env:
#             - name: REACT_APP_API_URL
#               value: "http://backend:9000"
#             - name: NODE_ENV
#               value: "production"
#           resources:
#             requests:
#               memory: "128Mi"
#               cpu: "100m"
#             limits:
#               memory: "256Mi"
#               cpu: "250m"
#           livenessProbe:
#             httpGet:
#               path: /
#               port: 3000
#             initialDelaySeconds: 30
#             periodSeconds: 10
#           readinessProbe:
#             httpGet:
#               path: /
#               port: 3000
#             initialDelaySeconds: 10
#             periodSeconds: 5
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: reservation-app
  labels:
    app: frontend
    app.kubernetes.io/name: reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/name: reservation-app
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: reservation-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
          image: faroukelrey19008/reservation-frontend:63
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80

          livenessProbe:
            httpGet:
              path: /
              port: 80


