apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reservation-app

resources:
  - namespace.yaml
  - database/deployment.yaml
  - database/service.yaml
  - backend/configmap.yaml
  - backend/secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml

commonLabels:
  app.kubernetes.io/name: reservation-app
  managed-by: argocd

commonAnnotations:
  description: "Reservation Management App"
