apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - service-backend.yaml

  - frontend-deployment.yaml
  - service-frontend.yaml

  - mysql-deployment.yaml
  - service-mysql.yaml
  - liquibase-job.yaml
