apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-app
  template:
    metadata:
      labels:
        app: reservation-app
    spec:
      containers: []   # ‚Üê EMPTY! Let overlays fill it