apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation-app
  template:
    metadata:
      labels:
        app: reservation-app
    spec:
      containers:
        - name: reservation-app
          image: farouk/reservation-app:latest
          ports:
            - containerPort: 9000
