apiVersion: v1
kind: Service
metadata:
  name: reservation-app
  namespace: reservation-app
  labels:
    app: reservation-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: frontend
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: backend
  selector:
    app: reservation-app