apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reservation-app-staging

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patch-rollout.yaml
    target:
      kind: Rollout
      name: reservation-app

labels:
  - pairs:
      environment: staging

secretGenerator:
  - name: mysql-secret
    behavior: replace
    literals:
      - password=staging1010
      - root-password=staging1010
      - database=reservation_db_staging
      - username=root
